## Introduction

This is a high-level introduction to hashing. You should walk away knowing what the following terms mean: *hash key*, *hash function*, *collision*, *linear probing*, *chaining*.

In [1]:
import numpy as np
from itertools import islice, cycle

In [2]:
def hasher(key, num_slots):
    '''Simple hashing function that returns hash value.
    Input:
        key: (int or str) thing to hash
        num_slots: (int) number of memory slots to allocate
    Output:
        (int) hash value
    '''
    
    assert type(key) == int or type(key) == str, "key must be an integer or string!"
    
    if type(key) == int:
        return key % num_slots
    elif type(key) == str:
        # sum the ASCII values to convert string to integer
        str2int = [ord(char) for char in list(key)]
        return np.sum(str2int) % num_slots

In [3]:
def answer(question):
    '''return answer to specific question'''
    
    if question == 1:
        print('We get a collision!')
    elif question == 2:
        print('1. change modulo number to a prime number')
        print('2. increase modulo number to create more buckets')
        print('3. extend hashing by adding additional functionality')
    elif question == 3:
        print('A prime is divisible only by itself and 1 so you do not have to worry about common factors.')
    elif question == 4:
        print('1. linear probing')
        print('2. chaining')

---

## A LITTLE ABOUT HASHING

**Hashing:** to convert a key to a numeric value with the goal of saving or returning a specific record in an array, table, database, etc. 

A **key** can be any unique value like a string or integer, for example. The numeric value returned is called a **hash key**, which represents the position to either store or lookup an item in a table. The hash key ranges between 0 and n-1. In this case, *n* is the maximum number of slots (aka buckets) in the array, table, or database.

The process of converting a key to a hash key is known as a **hash function**. It is used whenever access to the array, table, or database is needed.

## DISCLAIMER

This is only an introduction to hashing. It's a jumping off point really. There are so many cool things you can do with it. But for now just get the general idea.

#### EXAMPLE #1

In [4]:
table = np.zeros(8).astype('int')
table

array([0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
first = hasher(18, 8)
first

2

In [6]:
table[first] = 1
table

array([0, 0, 1, 0, 0, 0, 0, 0])

In [7]:
second = hasher('abc', 8)
second

6

In [8]:
table[second] = 2
table

array([0, 0, 1, 0, 0, 0, 2, 0])

In [9]:
third = hasher('ab', 8)
third

3

In [10]:
table[third] = 3
table

array([0, 0, 1, 3, 0, 0, 2, 0])

In [11]:
fourth = hasher('18', 8)
fourth

1

In [12]:
table[fourth] = 4
table

array([0, 4, 1, 3, 0, 0, 2, 0])

In [13]:
fifth = hasher('no', 8)
fifth

5

In [14]:
table[fifth] = 5
table

array([0, 4, 1, 3, 0, 5, 2, 0])

In [15]:
sixth = hasher(20, 8)
sixth

4

In [16]:
table[sixth] = 6
table

array([0, 4, 1, 3, 6, 5, 2, 0])

In [17]:
seventh = hasher('h', 8)
seventh

0

In [18]:
table[seventh] = 7
table

array([7, 4, 1, 3, 6, 5, 2, 0])

In [19]:
eighth = hasher('hello world+', 8)
eighth

7

In [20]:
table[eighth] = 8
table

array([7, 4, 1, 3, 6, 5, 2, 8])

## QUESTION #1

Now that we've filled all buckets in our table, what happens if we try to add another value?

In [21]:
answer(question=1)

We get a collision!


A collision happens when two different keys map to the same bucket. This is usually a problem, though not always. In this case, it is. 

## QUESTION #2

So what do we do about it?

In [22]:
answer(question=2)

1. change modulo number to a prime number
2. increase modulo number to create more buckets
3. extend hashing by adding additional functionality


## QUESTION #3

Why would changing the modulo number to a prime help avoid collisions?

In [23]:
answer(question=3)

A prime is divisible only by itself and 1 so you do not have to worry about common factors.


#### EXAMPLE #2

In [24]:
for i in range(8,88,8):
    print('index: {:2} | hash: {}'.format(i, hasher('hello world+', i)))

index:  8 | hash: 7
index: 16 | hash: 7
index: 24 | hash: 7
index: 32 | hash: 7
index: 40 | hash: 39
index: 48 | hash: 7
index: 56 | hash: 39
index: 64 | hash: 7
index: 72 | hash: 7
index: 80 | hash: 39


Yikes! That's a lot of collisions. 

In [25]:
for i in [7,11,13,17,19,23,29,31,37,41]:
    print('index: {:2} | hash: {}'.format(i, hasher('hello world+', i)))

index:  7 | hash: 4
index: 11 | hash: 4
index: 13 | hash: 2
index: 17 | hash: 3
index: 19 | hash: 0
index: 23 | hash: 9
index: 29 | hash: 28
index: 31 | hash: 12
index: 37 | hash: 12
index: 41 | hash: 11


We still get two collisions in this case but there far fewer of them. We could easily correct this by using larger primes.

**Side note:** you should clearly see how this relates to the **dictionary** data structure, which is nothing more than a hash table. It also explains why order is not **guaranteed**. If a collision occurs, the hash function is recomputed with a larger prime to create more memory slots (aka buckets). Therefore, a new hash function leads to new indices.  

#### EXAMPLE #3

In [26]:
mydict = {'a':1, 'b':2, 'c':3}

In [27]:
# here order is guaranteed
for _ in range(3):
    for k,v in mydict.items():
        print(k,v)
    print('---')

c 3
b 2
a 1
---
c 3
b 2
a 1
---
c 3
b 2
a 1
---


In [28]:
# let's add keys and values
mydict['d'] = 'o'
for k,v in mydict.items():
    print(k,v)
print('\n---\n')

mydict['e'] = 'm'
for k,v in mydict.items():
    print(k,v)
print('\n---\n')

mydict['f'] = 'g'
for k,v in mydict.items():
    print(k,v)

d o
c 3
b 2
a 1

---

d o
e m
c 3
b 2
a 1

---

c 3
e m
d o
a 1
b 2
f g


Notice the hash table (and order) was recomputed everytime we added a key?

---

## QUESTION #4

Can you think of a way to address collisions without resorting the methods above?

In [29]:
answer(question=4)

1. linear probing
2. chaining


## EXTEND HASH FUNCTION

Great. Now let's discuss some ways to extend our hashing function to handle collisions.

#### LINEAR PROBING

The idea of linear probing is simple. When a collision occurs, try the next index. If it's empty, is it. If not, try the next and the next and the next until you find one that works.

In [30]:
def updater(table, ix, value):
    '''Runs the linear search.
    
    Input: 
        table: numpy array initialized with all zeros the size of num_slots
        ix: (int) initial index to try
        value: (int) value to store
    '''
    while True:
        if np.all(table) != 0:
            print('all slots taken')
            break
        else:
            if table[ix] == 0:
                table[ix] = value
                break
            else:
                print('{} taken, linear searching...'.format(int(ix)))
                if ix+1 == table.size:  ## reset index if ix   
                    ix = 0               ## is last index value
                else:
                    ix += 1        
    return table

In [31]:
def linear_probe_hasher(table, value, key, num_slots):
    '''
    Input:
        table: numpy array initialized with all zeros the size of num_slots
        value: (int) value to store
        key: (int or str) thing to hash
        num_slots: (int) number of memory slots to allocate
    Output:
        (int) hash value
    '''
    
    assert len(table) == num_slots, "your table length does not match the number of slots!"
    assert type(key) == int or type(key) == str, "key must be an integer or string!"
    
    if type(key) == int:
        idx = key % num_slots
        return updater(table2, idx, value)
    elif type(key) == str:
        # sum the ASCII values to convert string to integer
        str2int = [ord(char) for char in list(key)]
        idx = np.sum(str2int) % num_slots
        return updater(table2, idx, 1)

#### EXAMPLE #4

In [32]:
table2 = np.zeros(5).astype('int')
table2

array([0, 0, 0, 0, 0])

In [33]:
# initial position
hasher(key=99, num_slots=5)

4

In [34]:
linear_probe_hasher(table2, value=1, key=99, num_slots=5)

array([0, 0, 0, 0, 1])

In [35]:
# let's purposely choose a collision
hasher(key=94, num_slots=5)

4

In [36]:
linear_probe_hasher(table2, value=2, key=94, num_slots=5)

4 taken, linear searching...


array([2, 0, 0, 0, 1])

In [37]:
# another collision
hasher(key=94, num_slots=5)

4

In [38]:
linear_probe_hasher(table2, value=3, key=94, num_slots=5)

4 taken, linear searching...
0 taken, linear searching...


array([2, 3, 0, 0, 1])

In [39]:
# another collision
hasher(key=94, num_slots=5)

4

In [40]:
linear_probe_hasher(table2, value=4, key=94, num_slots=5)

4 taken, linear searching...
0 taken, linear searching...
1 taken, linear searching...


array([2, 3, 4, 0, 1])

In [41]:
linear_probe_hasher(table2, value=5, key=94, num_slots=5)

4 taken, linear searching...
0 taken, linear searching...
1 taken, linear searching...
2 taken, linear searching...


array([2, 3, 4, 5, 1])

In [42]:
linear_probe_hasher(table2, value=4, key=94, num_slots=5)

all slots taken


array([2, 3, 4, 5, 1])

#### CHAINING
Chaining uses linked lists to append values in order when collisions occur.

In [43]:
def chain_hasher(table, value, key, num_slots):
    '''
    Input:
        table: list of lists
        value: (int) value to store
        key: (int or str) thing to hash
        num_slots: (int) number of memory slots to allocate
    Output:
        (int) hash value
    '''
    
    assert len(table) == num_slots, "your table length does not match the number of slots!"
    assert type(key) == int or type(key) == str, "key must be an integer or string!"
    
    if type(key) == int:
        idx = key % num_slots
        
    elif type(key) == str:
        # sum the ASCII values to convert string to integer
        str2int = [ord(char) for char in list(key)]
        idx = np.sum(str2int) % num_slots
        
    return table[idx].append(value)

#### EXAMPLE #5

In [44]:
table3 = [[],[],[],[],[]]
table3

[[], [], [], [], []]

In [45]:
chain_hasher(table3, 2, 'abc', 5)
table3

[[], [], [], [], [2]]

In [46]:
# purposely cause collision
chain_hasher(table3, 'collision!!!', 'abc', 5)
table3

[[], [], [], [], [2, 'collision!!!']]

## WHERE TO GO FROM HERE?

Lookup other hashing strategies.

Lookup other ways to handle collisions.

Lookup MD5, SHA-1, and other cryptographic hashes.