In [2]:
import scipy
import numpy as np

In [8]:
x = np.random.randint(1,10,size=10)
x

array([5, 1, 4, 9, 1, 4, 1, 8, 1, 4])

In [11]:
scipy.argsort(x)

array([1, 4, 6, 8, 2, 5, 9, 0, 7, 3])

In [40]:
scipy.piecewise(x, [x<5, x>=5], [-1,1])

array([ 1, -1, -1,  1, -1, -1, -1,  1, -1, -1])

In [56]:
np.vsplit(x.reshape(2,5), 2)

[array([[5, 1, 4, 9, 1]]), array([[4, 1, 8, 1, 4]])]