In [1]:
import numpy as np

## Concat

Add rows or columns to an existing array.

In [22]:
matrix1 = np.arange(20).reshape(10,2)
arr1 = np.arange(10, 30, 2)
arr2 = np.array([99,1001])
matrix2 = np.array([96,97,98,99]).reshape(2,2)

In [17]:
for array1, array2 in zip(matrix1, arr1):
    print(array1, array2)

[0 1] 10
[2 3] 12
[4 5] 14
[6 7] 16
[8 9] 18
[10 11] 20
[12 13] 22
[14 15] 24
[16 17] 26
[18 19] 28


### Add row(s) with axis=0

In [18]:
# add single row
np.concatenate((matrix1, arr2.reshape(1,-1)), axis=0)

array([[   0,    1],
       [   2,    3],
       [   4,    5],
       [   6,    7],
       [   8,    9],
       [  10,   11],
       [  12,   13],
       [  14,   15],
       [  16,   17],
       [  18,   19],
       [  99, 1001]])

In [5]:
# add multiple rows
np.concatenate((arr1, arr4), axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [96, 97],
       [98, 99]])

### Add column(s) with axis=1

In [6]:
# add column
np.concatenate((arr1, arr2.reshape(-1,1)), axis=1)

array([[ 0,  1, 10],
       [ 2,  3, 12],
       [ 4,  5, 14],
       [ 6,  7, 16],
       [ 8,  9, 18],
       [10, 11, 20],
       [12, 13, 22],
       [14, 15, 24],
       [16, 17, 26],
       [18, 19, 28]])

### Where is this useful?

Let's create a scenario where data is generated on-the-fly and needs appending to our array. Think data matrix here.

In [7]:
# with concatenate
for i in range(10):
    row = np.random.binomial(n=1, p=0.5, size=10).reshape(1,-1)
    if i == 0:
        array = np.array(row)
    else:
        array = np.concatenate((array, row), axis=0)
array

array([[1, 0, 1, 1, 1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 0, 0, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [8]:
array.shape

(10, 10)

### What about np.append()?

In [9]:
# with append 
for i in range(10):
    row = np.random.binomial(n=1, p=0.5, size=10).reshape(1,-1)
    if i == 0:
        array = np.array(row)
    else:
        array = np.append(array, row, axis=0)
array

array([[1, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1, 1],
       [1, 0, 0, 1, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 1, 0]])

In [10]:
array.shape

(10, 10)

It turns out that **np.append()** uses **np.concatenate()** under the hood. You may as well just use **np.concatenate()** since that's the case. It's faster for the same reason.

## Ravel

Return a contiguous flattened 1D array.

In [24]:
matrix1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [26]:
# C order is row-wise
ravel_C = np.ravel(matrix1, 'C')
ravel_C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
ravel_C.shape

(20,)

In [28]:
# F order is column-wise
ravel_F = np.ravel(matrix1, 'F')
ravel_F

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  1,  3,  5,  7,  9, 11, 13,
       15, 17, 19])

In [29]:
ravel_F.shape

(20,)

In [30]:
tensor3d = np.arange(27).reshape(3,3,3)
tensor3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
np.ravel(tensor3d, 'C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [35]:
np.ravel(tensor3d, 'F')

array([ 0,  9, 18,  3, 12, 21,  6, 15, 24,  1, 10, 19,  4, 13, 22,  7, 16,
       25,  2, 11, 20,  5, 14, 23,  8, 17, 26])

## Mesh-grid

Returns a dense multi-dimensional “meshgrid”.

In [47]:
# first range sets number of rows and its values 
# second range sets number of cols and its values
grid1 = np.mgrid[1:10:2,0:10:2]
grid1

array([[[1, 1, 1, 1, 1],
        [3, 3, 3, 3, 3],
        [5, 5, 5, 5, 5],
        [7, 7, 7, 7, 7],
        [9, 9, 9, 9, 9]],

       [[0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8],
        [0, 2, 4, 6, 8]]])

In [48]:
grid1.shape

(2, 5, 5)

In [49]:
grid2 = np.mgrid[-100:100:5, range(3)]
grid2

array([[[-100, -100, -100],
        [ -95,  -95,  -95],
        [ -90,  -90,  -90],
        [ -85,  -85,  -85],
        [ -80,  -80,  -80],
        [ -75,  -75,  -75],
        [ -70,  -70,  -70],
        [ -65,  -65,  -65],
        [ -60,  -60,  -60],
        [ -55,  -55,  -55],
        [ -50,  -50,  -50],
        [ -45,  -45,  -45],
        [ -40,  -40,  -40],
        [ -35,  -35,  -35],
        [ -30,  -30,  -30],
        [ -25,  -25,  -25],
        [ -20,  -20,  -20],
        [ -15,  -15,  -15],
        [ -10,  -10,  -10],
        [  -5,   -5,   -5],
        [   0,    0,    0],
        [   5,    5,    5],
        [  10,   10,   10],
        [  15,   15,   15],
        [  20,   20,   20],
        [  25,   25,   25],
        [  30,   30,   30],
        [  35,   35,   35],
        [  40,   40,   40],
        [  45,   45,   45],
        [  50,   50,   50],
        [  55,   55,   55],
        [  60,   60,   60],
        [  65,   65,   65],
        [  70,   70,   70],
        [  75,   75,

In [50]:
grid2.shape

(2, 40, 3)