In [1]:
import numpy as np

In [2]:
X = np.array([12,6,3,4,5,6,7,8,9]).reshape(3,3)
Y = np.array([5,8,1,2,6,7,3,0,4,5,9,1]).reshape(3,4)

In [3]:
X

array([[12,  6,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [4]:
Y

array([[5, 8, 1, 2],
       [6, 7, 3, 0],
       [4, 5, 9, 1]])

In [5]:
rows, cols = X.shape[0], Y.shape[1]
result = np.zeros(rows * cols).reshape(rows, cols)

# iterate through rows of X
for i in range(rows):
   # iterate through columns of Y
   for j in range(cols):
       # iterate through rows of Y
       for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

# Q1: What does this block of code do?

# Q2: What's the complexity?

## Show Results

In [6]:
result

array([[ 108.,  153.,   57.,   27.],
       [  74.,   97.,   73.,   14.],
       [ 119.,  157.,  112.,   23.]])

In [7]:
np_result = np.dot(X,Y)
np_result

array([[108, 153,  57,  27],
       [ 74,  97,  73,  14],
       [119, 157, 112,  23]])

In [8]:
np.allclose(result, np_result)

True

# Answers

## Q1: Matrix-Matrix multiplication
## Q2: if m = rows of X, n = cols of Y and p = rows of Y --> O($mnp$) 