In [1]:
import numpy as np

## Bubble Sort
Bubble sort is described in detail on [Wikipedia](https://en.wikipedia.org/wiki/Bubble_sort).

Its complexity is $O(n^2)$.

In [2]:
def bubble_sort(array, verbose=False):
    '''The bubble sort algorithm.
    
    INPUT: array or list
    OUTPUT: sorted array or list
    '''
    
    # setup
    unsorted = True
    list_length = len(array) - 1
    
    # main logic
    while unsorted:
        changes = 0
        for i in range(list_length):
            if mylist[i] > mylist[i+1]:
                mylist[i], mylist[i+1] = mylist[i+1], mylist[i]
                changes += 1
        if not changes:
            unsorted = False
        if verbose:
            print(mylist)

In [3]:
mylist = np.random.randint(0, 50, 25)
mylist

array([39, 40, 35, 46, 11, 33, 23, 14, 38, 32,  1, 10, 16, 34, 26, 22, 23,
       10, 12, 11, 10,  0,  6, 10, 31])

In [4]:
bubble_sort(mylist, verbose=True)

[39 35 40 11 33 23 14 38 32  1 10 16 34 26 22 23 10 12 11 10  0  6 10 31 46]
[35 39 11 33 23 14 38 32  1 10 16 34 26 22 23 10 12 11 10  0  6 10 31 40 46]
[35 11 33 23 14 38 32  1 10 16 34 26 22 23 10 12 11 10  0  6 10 31 39 40 46]
[11 33 23 14 35 32  1 10 16 34 26 22 23 10 12 11 10  0  6 10 31 38 39 40 46]
[11 23 14 33 32  1 10 16 34 26 22 23 10 12 11 10  0  6 10 31 35 38 39 40 46]
[11 14 23 32  1 10 16 33 26 22 23 10 12 11 10  0  6 10 31 34 35 38 39 40 46]
[11 14 23  1 10 16 32 26 22 23 10 12 11 10  0  6 10 31 33 34 35 38 39 40 46]
[11 14  1 10 16 23 26 22 23 10 12 11 10  0  6 10 31 32 33 34 35 38 39 40 46]
[11  1 10 14 16 23 22 23 10 12 11 10  0  6 10 26 31 32 33 34 35 38 39 40 46]
[ 1 10 11 14 16 22 23 10 12 11 10  0  6 10 23 26 31 32 33 34 35 38 39 40 46]
[ 1 10 11 14 16 22 10 12 11 10  0  6 10 23 23 26 31 32 33 34 35 38 39 40 46]
[ 1 10 11 14 16 10 12 11 10  0  6 10 22 23 23 26 31 32 33 34 35 38 39 40 46]
[ 1 10 11 14 10 12 11 10  0  6 10 16 22 23 23 26 31 32 33 34 35 38 39 40 46]