In [1]:
import numpy as np

In [2]:
def find_w(a, b):
    '''function that returns solution to a*w=b, if it exists'''
    # check if 1D or 2D array
    if len(a.shape) != 2:
        # reshape if 1D array, else throws error
        a = a.reshape(-1,1)
        try:
            return np.linalg.solve(a,b)
        except:
            print('Warning: Singular Matrix')  ## case where a=0 and b!=0
    else:
        # num rows < num columns = infinite solutions
        if a.shape[0] < a.shape[1]:
            print('Underdetermined System: infinite or no solutions')
        else:
            try:
                return np.linalg.solve(a,b)
            except:
                print('0 solutions')

### Example Problem

In [3]:
X = np.array([5,3,7,2,4,1]).reshape(2,3)
y = np.array([537, 241])
print(X)
print()
print(y)

[[5 3 7]
 [2 4 1]]

[537 241]


In [4]:
find_w(X,y)

Underdetermined System: infinite or no solutions


** *This is an underdetermined systems as there are 2 equations and 3 variables. Therefore, there exist an infinite number of solutions.* **

### Example A

In [5]:
X = np.array([2])
y = np.array([8])
find_w(X,y)

array([ 4.])

### Example B

In [6]:
X = np.array([0])
y = np.array([8])
find_w(X,y)

** *No solution. Zero times anything is always zero!* **

### Example C

In [7]:
X = np.array([2,4])
y = np.array([8])
find_w(X,y)

np.linalg.solve expects square matrix so disregard message. Infinite solutions for this one. Underdetermined.

### Example D

In [8]:
X = np.array([2,4,0,1]).reshape(2,2)
y = np.array([8,3])
find_w(X,y)

array([-2.,  3.])

### Example E

In [9]:
X = np.array([2,4,0,1,9,5]).reshape(3,2)
y = np.array([8,3,1])
find_w(X,y)

0 solutions


### Example F

In [10]:
X = np.array([2,2,3,3]).reshape(2,2)
y = np.array([4,6])
find_w(X,y)

array([ 2.,  0.])

Actually infinite solutions because same equation twice, just with different coefficients. Really have 1 unique equation with 2 unknowns. Underdetermined. Need to catch this edge case in code.

### Example G

Can't be done. Can't multiply text * numbers.

### Example H

In [11]:
X = np.array([1,0,0,1]).reshape(2,2)
y = np.array([8,6])
find_w(X,y)

array([ 8.,  6.])

### Example I

In [12]:
X = np.array([1,1,0,1,0,1]).reshape(2,3)
y = np.array([8,6])
find_w(X,y)

Underdetermined System: infinite or no solutions


### Example J

In [13]:
X = np.array([1,0,1,1]).reshape(2,2)
y = np.array([8,6])
find_w(X,y)

array([ 8., -2.])

### NOTES

An **underdetermined** system is one in which there are fewer equations than unknowns. The result is either 0 or infinite solutions. There are 0 solutions when equations are inconsistent. For example, x+y=1 and x+y=2. That can't possibly be because the same equation gives different outputs. There are infinite solutions otherwise.

An **overdetermined** system is one in which there are more equations than unknowns. Be wary of inconsistent equations (x+y=1 and x+y=2) that will cause this system to have 0 solutions. Otherise a unique solution exists.

**Takeaway:** *so long as the number of unique equations is at least the same as the number of variables AND there are no inconsistencies, a unique solution exists.*