## OBJECTIVE

This is a brief introduction to Jupyter notebooks and the basics of Python. 

There is so much more to both of these but this will get you off and running.

## JUPYTER OVERVIEW

Key concepts:

* Key uses of Jupyter notebooks
* When not to use
* Sequential process: the good and the bad
* Brief tour

---

## MARKDOWN

Here's a [link](https://dziganto.github.io/) to my blog.

Let's **bold** some text.

How about *italicize*.

A picture? ![elmhurst college](http://static.panoramio.com/photos/large/61667921.jpg)

Here's a **bulleted** list:
* sub-bullet 1
* sub-bullet 2
* sub-bullet 3

Here's a **numbered** list:
1. item 1
2. item 2
3. item 3

A little LaTeX:

$e^{{i}{\pi}} + 1 = 0$

$$\frac{df}{dt} = \lim_{h \to 0} \frac{f(t+h)-f(t)}{h}$$

Lastly, let's include a gif:
![Gif](https://media.giphy.com/media/Cm61Cmevc70Va/giphy.gif)

---

In [1]:
# Writing code
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


---

## PRINT

In [2]:
print('This is a sentence.')

This is a sentence.


In [3]:
print("Here's a sentence with an apostrophe. Notice the double quotes around these sentences.")

Here's a sentence with an apostrophe. Notice the double quotes around these sentences.


In [4]:
print('Here is a quote:\n\n"Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."')

Here is a quote:

"Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."


In [5]:
print('Multiple')
print('print')
print('statements')
print('in')
print('one')
print('cell')

Multiple
print
statements
in
one
cell


---

## COMMAND LINE

In [6]:
# python version
! python -V

Python 3.5.4 :: Anaconda custom (64-bit)


In [7]:
# python path
! which python

/Users/davidziganto/anaconda/bin/python


---

## NAMESPACE

In [8]:
who # check variables and modules loaded into memory

No variables match your requested type.


In [9]:
whos # like 'who' but easier to read

No variables match your requested type.


We'll use *who* and *whos* again shortly. For now, just know what they are.

---

## LOOPS

#### 1) For Loop

In [10]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [11]:
for i in range(3):
    print("i:{}".format(i))
    for j in range(1,3):
        print("  j:{}".format(j))

i:0
  j:1
  j:2
i:1
  j:1
  j:2
i:2
  j:1
  j:2


#### 2) While Loop

In [12]:
count = 1
while count <= 10:
    print('count|' * count)
    count += 1
else:
    print('\nThe End!')

count|
count|count|
count|count|count|
count|count|count|count|
count|count|count|count|count|
count|count|count|count|count|count|
count|count|count|count|count|count|count|
count|count|count|count|count|count|count|count|
count|count|count|count|count|count|count|count|count|
count|count|count|count|count|count|count|count|count|count|

The End!


---

## CONDITIONAL STATEMENTS

In [13]:
indicator = True
if indicator == True:
    print('Yay, the indicator is true!')
else:
    print('Nothing to see here. Move along.')

Yay, the indicator is true!


In [14]:
# same as above but Python defaults to True so no need to set equal to True
indicator = True
if indicator:
    print('Yay, the indicator is true!')
else:
    print('Nothing to see here. Move along.')

Yay, the indicator is true!


In [15]:
indicator = False
if indicator == True:
    print('Yay, the indicator is true!')
else:
    print('Nothing to see here. Move along.')

Nothing to see here. Move along.


#### Tangent: Truthiness

In [16]:
indicator == True

False

In [17]:
indicator == False

True

In [18]:
indicator != False

False

In [19]:
True == 1

True

In [20]:
indicator == 1

False

**[Your Turn]**

Experiment to see which values are True and which False.

In [21]:
indicator = 2
if indicator:
    print('Yay, the indicator is true!')
else:
    print('Nothing to see here. Move along.')

Yay, the indicator is true!


---

## FUNCTIONS

In [22]:
def print_function():
    '''this function prints 'hello world'.'''
    print('hello world')

In [23]:
print_function()

hello world


In [24]:
def print_input(text):
    '''this function prints the user's text.'''
    # error handling
    assert type(text) == str, "you must input text in string format!"
    print(text)

In [25]:
print_input('hi there')

hi there


In [26]:
print_input(21)

AssertionError: you must input text in string format!

In [27]:
def print_input2(text):
    '''this function prints the user's text.'''
    # error handling
    if type(text) != str:
        text = str(text)
    assert type(text) == str, "wrong format!" # just to prove a point
    print(text)

In [28]:
print_input2(21)

21


In [29]:
def square_num(num):
    '''this function takes a number called num and square it.'''
    return num ** 2

In [30]:
square_num(4)

16

In [31]:
square_num(10)

100

#### [Your Turn]

Write a function called **fizzbuzz** that returns 'fizz' if a number is divisible by 3, 'buzz' if divisible by 5, 'fizzbuzz' if divisible by 15, or the number otherwise. Allow the user to input a number.

In [32]:
def fizzbuzz(num):
    '''classic fizzbuzz function.'''
    if num==0:
        return 0
    else: 
        if num%15==0:
            return 'fizzbuzz'
        elif num%5==0:
            return 'buzz'
        elif num%3==0:
            return 'fizz'
        else:
            return num

In [33]:
# test your function with this code
for i in range(21):
    print(fizzbuzz(i))

0
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz


## DATA STRUCTURES

### 1) LIST

* Mutable  
* Mixed-type

Lists are ordered sets of objects. They are powerful, flexible, and one of the most widely used data structures in all of Python.

In [34]:
mylist = [99, 'text', 3.14159]
mylist

[99, 'text', 3.14159]

In [35]:
# print list items (BAD WAY - DON'T EVER DO THIS!!!)
for i in range(len(mylist)):
    print(mylist[i])

99
text
3.14159


In [36]:
# Pythonic way to print list items
for item in mylist:
    print(item)

99
text
3.14159


In [37]:
# enumerate if you need item AND index value
for i, item in enumerate(mylist):
    print('i: {} | item: {}'.format(i, item))

i: 0 | item: 99
i: 1 | item: text
i: 2 | item: 3.14159


In [38]:
# you can set starting index
for i, item in enumerate(mylist, 1):
    print('i: {} | item: {}'.format(i, item))

i: 1 | item: 99
i: 2 | item: text
i: 3 | item: 3.14159


In [39]:
# append to list
mylist.append('new text')
mylist

[99, 'text', 3.14159, 'new text']

In [40]:
# delete 2nd item
mylist.pop(1)
mylist

[99, 3.14159, 'new text']

In [41]:
# delete last item
mylist.pop()
mylist

[99, 3.14159]

In [42]:
# update value of 2nd item
mylist[1] = 2.71828
mylist

[99, 2.71828]

#### [Your Turn]

Create a list called **alphanums** that is composed of lists. Specifically, make a list of the letters **A-E** with corresponding location in alphabet. Example: **['A', 1], ['B', 2]**.

In [43]:
alphanums = [['A',1], ['B',2], ['C',3], ['D',4], ['E',5]]
alphanums

[['A', 1], ['B', 2], ['C', 3], ['D', 4], ['E', 5]]

Iterate over this list of lists returning only the letters from each sublist.

In [44]:
for sublist in alphanums:
    print(sublist[0])

A
B
C
D
E


In [45]:
# advanced version w/zip
for alpha, num in zip(list('ABCDE'), range(1,6)):
    print(alpha)

A
B
C
D
E


#### LIST COMPREHENSION w/even numbers

In [46]:
# typical list with for loop and if statement
mylist2 = []
for i in range(10):
    if i%2 == 0:
        mylist2.append(i)
mylist2

[0, 2, 4, 6, 8]

In [47]:
mylist3 = [i for i in range(10) if i%2 == 0]
mylist3

[0, 2, 4, 6, 8]

In [48]:
# check if same values
mylist2 == mylist3

True

In [49]:
# check if same object
mylist2 is mylist3

False

#### [Your Turn - Advanced Fizzbuzz (Optional)]

Can you write a list expression that returns 'fizz' if a number is divisible by 3, 'buzz' if divisible by 5, 'fizzbuzz' if divisible by 15, or the number otherwise? Do this for numbers 1-20.

In [50]:
['fizzbuzz' if i%15==0 else 'fizz' if i%3==0 else 'buzz' if i%5==0 else i for i in range(1, 21)]

[1,
 2,
 'fizz',
 4,
 'buzz',
 'fizz',
 7,
 8,
 'fizz',
 'buzz',
 11,
 'fizz',
 13,
 14,
 'fizzbuzz',
 16,
 17,
 'fizz',
 19,
 'buzz']

#### 1b) GENERATOR COMPREHENSION - Memory Efficient

In [51]:
# generator version of fizzbuzz
def fizzbuzz_gen():
    i = 1
    while True:
        if i%15 == 0:
            yield 'fizzbuzz'
        elif i%5 == 0:
            yield 'buzz'
        elif i%3 == 0:
            yield 'fizz'
        else:
            yield i
        i += 1

In [52]:
fbg = fizzbuzz_gen()

In [53]:
type(fbg)

generator

In [54]:
for _ in range(21):
    print(next(fbg))

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz


### 2) TUPLE

* Immutable
* Mixed-type

Tuples are often described as immutable lists. Because tuples are immutable they are often faster than lists. Tuples are perfect if you want to ensure the values don't change too. So if you're looking for flexibility, go with a list. Otherwise, go with a tuple.

In [55]:
myfirstuple = (99, 'text', 3.14159)
myfirstuple

(99, 'text', 3.14159)

In [56]:
myfirstuple[1]

'text'

In [57]:
myfirstuple[1] = 0

TypeError: 'tuple' object does not support item assignment

---

Let's check our namespace now.

In [58]:
whos

Variable         Type         Data/Info
---------------------------------------
alpha            str          E
alphanums        list         n=5
count            int          11
fbg              generator    <generator object fizzbuzz_gen at 0x1086cd4c0>
fizzbuzz         function     <function fizzbuzz at 0x1086f5048>
fizzbuzz_gen     function     <function fizzbuzz_gen at 0x1086f2d90>
i                int          9
indicator        int          2
item             float        3.14159
j                int          2
myfirstuple      tuple        n=3
mylist           list         n=2
mylist2          list         n=5
mylist3          list         n=5
num              int          5
print_function   function     <function print_function at 0x10868c1e0>
print_input      function     <function print_input at 0x10864cd08>
print_input2     function     <function print_input2 at 0x1087000d0>
square_num       function     <function square_num at 0x108700400>
sublist          list         n=2

In [59]:
# delete something from namespace
del indicator

In [60]:
whos

Variable         Type         Data/Info
---------------------------------------
alpha            str          E
alphanums        list         n=5
count            int          11
fbg              generator    <generator object fizzbuzz_gen at 0x1086cd4c0>
fizzbuzz         function     <function fizzbuzz at 0x1086f5048>
fizzbuzz_gen     function     <function fizzbuzz_gen at 0x1086f2d90>
i                int          9
item             float        3.14159
j                int          2
myfirstuple      tuple        n=3
mylist           list         n=2
mylist2          list         n=5
mylist3          list         n=5
num              int          5
print_function   function     <function print_function at 0x10868c1e0>
print_input      function     <function print_input at 0x10864cd08>
print_input2     function     <function print_input2 at 0x1087000d0>
square_num       function     <function square_num at 0x108700400>
sublist          list         n=2
this             module       <

In [61]:
# delete multiple items
del i,j

In [62]:
whos

Variable         Type         Data/Info
---------------------------------------
alpha            str          E
alphanums        list         n=5
count            int          11
fbg              generator    <generator object fizzbuzz_gen at 0x1086cd4c0>
fizzbuzz         function     <function fizzbuzz at 0x1086f5048>
fizzbuzz_gen     function     <function fizzbuzz_gen at 0x1086f2d90>
item             float        3.14159
myfirstuple      tuple        n=3
mylist           list         n=2
mylist2          list         n=5
mylist3          list         n=5
num              int          5
print_function   function     <function print_function at 0x10868c1e0>
print_input      function     <function print_input at 0x10864cd08>
print_input2     function     <function print_input2 at 0x1087000d0>
square_num       function     <function square_num at 0x108700400>
sublist          list         n=2
this             module       <module 'this' from '/Use<...>a/lib/python3.5/this.py'>


---

### 3) DICTIONARY

* Keys are immutable
* Values are mutable
* Keys mapped to values via hashing
* Incredibly fast lookups (constant time)
* Significant memory overhead (to store hash table)

Dictionaries are unordered sets. Items in a dictionary are accessed via keys (not by index as in a list). Each key of the dictionary must be immutable and is mapped to a value. The values of a dictionary can be any Python data type. In other words, dictionaries are unordered key-value pairs. 

In [63]:
mydict = {'a':1, 'b':2, 'c':['apple', 'orange', 'banana']}
mydict

{'a': 1, 'b': 2, 'c': ['apple', 'orange', 'banana']}

In [64]:
mydict['a']

1

In [65]:
mydict['c']

['apple', 'orange', 'banana']

In [66]:
mydict['c'][1]

'orange'

In [67]:
# slicing from index to end
mydict['c'][1:]

['orange', 'banana']

In [68]:
# slicing from start to index
mydict['c'][:1]

['apple']

In [69]:
# dictionary comprehension
mydict2 = {key: i**2 for key, i in zip(list('ABCDE'), range(5))}
mydict2

{'A': 0, 'B': 1, 'C': 4, 'D': 9, 'E': 16}

### 4) SET

* Mutable
* Unique values
* Great for testing membership

A set is an ordered collection of unique and immutable objects. It's highly optimized for testing membership. So if you're thinking about using "in" to test membership, think again - sets are much, much faster!

In [70]:
list_of_duplicates = [1, 2, 2, 2, 3, 4, 5, 5]
list_of_duplicates

[1, 2, 2, 2, 3, 4, 5, 5]

In [71]:
2 in list_of_duplicates

True

In [72]:
myset = set(list_of_duplicates)
myset

{1, 2, 3, 4, 5}

In [73]:
2 in myset

True

## ARRAYS & NUMPY

* Mutable
* Single-type
* Fast loading/saving

An array is much more efficient than a list if you're only looking to store a single object type like an integer, float, or string. 

In [74]:
import numpy as np

In [75]:
myfirstarray = np.arange(100)
myfirstarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [76]:
# vectorized version of even numbers (FAST!!!)
myfirstarray[myfirstarray%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [77]:
# vectorized version of numbers between 25 and 75 exclusive (FAST!!!)
myfirstarray[(myfirstarray>25) & (myfirstarray<75)]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74])

In [78]:
# vectorized version of even numbers between 25 and 75 exclusive (FAST!!!)
myfirstarray[(myfirstarray>25) & (myfirstarray<75) & (myfirstarray%2==0)]

array([26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58,
       60, 62, 64, 66, 68, 70, 72, 74])

In [79]:
matrix = np.random.randint(low=1, high=100, size=100).reshape(25,4)
matrix

array([[31, 36,  9, 45],
       [10, 78, 81, 39],
       [38, 85, 65, 96],
       [90, 21, 34, 31],
       [94,  5, 54, 89],
       [41, 22, 57, 74],
       [52,  8, 46, 92],
       [67, 67, 82, 87],
       [18, 74, 73, 95],
       [78, 81, 57, 25],
       [99, 70, 81, 91],
       [44, 21, 19, 84],
       [50,  4, 83, 48],
       [45, 73, 51, 75],
       [98, 10, 42, 32],
       [41, 17, 20, 58],
       [58, 14, 36, 85],
       [89, 94, 92, 46],
       [31, 28, 18, 17],
       [ 1, 45,  2, 80],
       [48, 29, 34, 36],
       [95, 50, 36, 11],
       [58,  9,  1,  7],
       [44, 54, 52, 11],
       [23,  5, 59, 22]])

In [80]:
matrix.shape

(25, 4)

## TIMEIT

A quick and easy way to test how long code takes to run.

In [81]:
testlist = list(range(int(1e6)))
len(testlist)

1000000

In [82]:
testarray = np.arange(1e6)
testarray.shape

(1000000,)

In [83]:
%%timeit
[i for i in testlist if i%2==0]

227 ms ± 6.61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [84]:
%%timeit
testarray[testarray%2==0]

13.7 ms ± 189 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [85]:
13.7/227

0.06035242290748898

## THERE ARE A FEW OTHER LIBRARIES YOU SHOULD KNOW ABOUT

**1) [Matplotlib - plotting](http://matplotlib.org/tutorials/index.html)**  
**2) [Pandas - data structures and analysis](http://pandas.pydata.org/pandas-docs/stable/10min.html)**  
**3) [Scipy - scientific computing](https://docs.scipy.org/doc/numpy/user/quickstart.html)**  
**4) [Sklearn - machine learning](http://scikit-learn.org/stable/index.html)**  

## I'll cover some Matplotlib, Pandas, and Sci-Kit Learn in the next session so stay tuned.