In [1]:
import numpy as np

In [2]:
fake_data = np.random.randint(0,100,100).reshape(10,10)
fake_data

array([[71, 36,  4, 82, 30, 21,  6, 86, 25, 64],
       [88,  7, 46, 24, 45, 77, 45, 92, 24, 88],
       [28, 85, 25, 26, 61, 76, 70, 83, 16, 62],
       [38, 57, 84, 85, 62, 82, 91, 31, 20, 23],
       [28, 54, 13, 44, 34, 23,  1, 71, 88, 21],
       [62, 60,  0, 29,  8, 99, 82, 49, 45, 54],
       [11, 16, 31, 99, 75, 48, 84, 52, 62, 39],
       [47, 56, 35, 49, 41, 95, 40, 77, 30, 56],
       [79, 91, 66, 78, 22, 50,  3, 57, 98, 92],
       [97, 60, 21, 89, 17, 76, 25, 72, 22, 10]])

In [65]:
def train_test_split(data, shuffle=True, test_proportion=0.2, random_state=None):
    '''return train and test sets'''
    
    # error checking
    assert type(shuffle) == bool, 'shuffle must be True or False!'
    if random_state != None:
        assert type(random_state) == int, 'random_state must be an integer!'
    
    # reproducibility
    if random_state:
        np.random.seed(random_state)
    
    # setup indices
    indices = np.arange(data.shape[0])
    if shuffle:
        np.random.shuffle(indices)
    
    # main logic
    num_indices = len(indices)
    split = int( np.floor(test_proportion * num_indices) )
    train = data[indices[:split]]
    test = data[indices[split:]]
    
    return train, test

In [67]:
train, test = train_test_split(fake_data, shuffle=True, test_proportion=0.4, random_state=43)

In [68]:
train

array([[38, 57, 84, 85, 62, 82, 91, 31, 20, 23],
       [97, 60, 21, 89, 17, 76, 25, 72, 22, 10],
       [11, 16, 31, 99, 75, 48, 84, 52, 62, 39],
       [79, 91, 66, 78, 22, 50,  3, 57, 98, 92]])

In [69]:
test

array([[28, 85, 25, 26, 61, 76, 70, 83, 16, 62],
       [62, 60,  0, 29,  8, 99, 82, 49, 45, 54],
       [88,  7, 46, 24, 45, 77, 45, 92, 24, 88],
       [47, 56, 35, 49, 41, 95, 40, 77, 30, 56],
       [71, 36,  4, 82, 30, 21,  6, 86, 25, 64],
       [28, 54, 13, 44, 34, 23,  1, 71, 88, 21]])