## OBJECTIVE

This is a tutorial meant to introduce you to PyTorch, a python package that provides two high-level features:
1. A replacement for numpy to use the power of GPUs
2. A deep learning research platform that provides maximum flexibility and speed  

According to the [docs](http://pytorch.org/about/):
>**[DYNAMIC NEURAL NETWORKS]**  
>"PyTorch has a unique way of building neural networks: using and replaying a tape recorder."
>
>"Most frameworks such as TensorFlow, Theano, Caffe and CNTK have a static view of the world. One has to build a neural network, and reuse the same structure again and again. Changing the way the network behaves means that one has to start from scratch."
>
>"With PyTorch, we use a technique called Reverse-mode auto-differentiation, which allows you to change the way your network behaves arbitrarily with zero lag or overhead. Our inspiration comes from several research papers on this topic, as well as current and past work such as autograd, autograd, Chainer, etc."
>
>"While this technique is not unique to PyTorch, it’s one of the fastest implementations of it to date. You get the best of speed and flexibility for your crazy research."
>
> 
>**[NATIVE TO PYTHON]**  
>"PyTorch is not a Python binding into a monolothic C++ framework. It is built to be deeply integrated into Python. You can use it naturally like you would use numpy / scipy / scikit-learn etc. You can write your new neural network layers in Python itself, using your favorite libraries and use packages such as Cython and Numba. Our goal is to not reinvent the wheel where appropriate."
>
>**[EASY TO USE]**  
>"PyTorch is designed to be intuitive, linear in thought and easy to use. When you execute a line of code, it gets executed. There isn’t an asynchronous view of the world. When you drop into a debugger, or receive error messages and stack traces, understanding them is straight-forward. The stack-trace points to exactly where your code was defined. We hope you never spend hours debugging your code because of bad stack traces or asynchronous and opaque execution engines."
>
>**[FAST]**  
>"PyTorch has minimal framework overhead. We integrate acceleration libraries such as Intel MKL and NVIDIA (CuDNN, NCCL) to maximize speed. At the core, it’s CPU and GPU Tensor and Neural Network backends (TH, THC, THNN, THCUNN) are written as independent libraries with a C99 API."
>
>"They are mature and have been tested for years."
>
>"Hence, PyTorch is quite fast – whether you run small or large neural networks."
>
>**[LEAN]**  
>"The memory usage in PyTorch is extremely efficient compared to Torch or some of the alternatives. We’ve written custom memory allocators for the GPU to make sure that your deep learning models are maximally memory efficient. This enables you to train bigger deep learning models than before."

---

In [1]:
import torch
import numpy as np

## Arrays vs Tensors

In [2]:
arr = np.array([1,2,3,4], dtype=float)
arr

array([1., 2., 3., 4.])

In [3]:
tensor = torch.Tensor([1,2,3,4])
tensor


 1
 2
 3
 4
[torch.FloatTensor of size 4]

#### Convert torch tensor to numpy array

In [4]:
tensor2arr = tensor.numpy()
tensor2arr

array([1., 2., 3., 4.], dtype=float32)

In [5]:
tensor2arr == arr

array([ True,  True,  True,  True])

#### Convert numpy array to torch tensor

In [6]:
arr2tensor = torch.from_numpy(arr)
arr2tensor


 1
 2
 3
 4
[torch.DoubleTensor of size 4]

The returned tensor and ndarray share the same memory.

## A Useful Torch Methods

#### **is_tensor:** checks if torch tensor

In [7]:
torch.is_tensor(arr)

False

In [8]:
torch.is_tensor(tensor)

True

#### **numel:** returns total number of elements in tensor

In [9]:
torch.numel(tensor)

4

**set_printoptions:** set options for printing

In [17]:
long_array = torch.Tensor([1/9, 1/11, 1/13, 1/14, 1/17, 1/19])
long_array


 0.1111
 0.0909
 0.0769
 0.0714
 0.0588
 0.0526
[torch.FloatTensor of size 6]

In [26]:
torch.set_printoptions(precision=4, threshold=5, edgeitems=1)

In [27]:
long_array


 0.1111
   ⋮   
 0.0526
[torch.FloatTensor of size 6]

In [20]:
torch.set_printoptions(precision=2, threshold=1, edgeitems=2)

In [21]:
long_array


   0.11
   0.09
   ⋮   
   0.06
   0.05
[torch.FloatTensor of size 6]

In [29]:
torch.set_printoptions(precision=8, threshold=1000, edgeitems=3)

In [30]:
long_array


0.11111111
0.09090909
0.07692308
0.07142857
0.05882353
0.05263158
[torch.FloatTensor of size 6]

**eye:** identity matrix

In [31]:
torch.eye(5)


 1  0  0  0  0
 0  1  0  0  0
 0  0  1  0  0
 0  0  0  1  0
 0  0  0  0  1
[torch.FloatTensor of size 5x5]

#### **linspace**: tensor of equally spaced points

In [32]:
torch.linspace(10, 1, steps=9)


10.00000000
8.87500000
7.75000000
6.62500000
5.50000000
4.37500000
3.25000000
2.12500000
1.00000000
[torch.FloatTensor of size 9]

#### **arange:** just like numpy's arange

In [33]:
torch.arange(0, 10)


 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
[torch.FloatTensor of size 10]

#### **randn:** random numbers from standard normal

In [34]:
matrix = torch.randn(3, 3)
matrix


-0.38017491 -0.18355389 -1.84704256
-0.26852292 0.39609560 -1.90073419
0.04706057 0.98052627 -0.50285697
[torch.FloatTensor of size 3x3]

## **transpose:** self-explanatory

In [35]:
matrix.t()


-0.38017491 -0.26852292 0.04706057
-0.18355389 0.39609560 0.98052627
-1.84704256 -1.90073419 -0.50285697
[torch.FloatTensor of size 3x3]

## Random Numbers

In [38]:
probs = torch.Tensor([0.3, 0.7])
torch.bernoulli(probs)


 0
 1
[torch.FloatTensor of size 2]

In [39]:
torch.normal(mean=0.5, std=torch.arange(1, 6))


0.73442763
1.37034154
3.81558180
5.52552414
-9.05425358
[torch.FloatTensor of size 5]

In [40]:
torch.rand(9)


0.20026210
0.25436735
0.76207173
0.66632295
0.28561437
0.04027488
0.58041018
0.46796060
0.63385683
[torch.FloatTensor of size 9]

In [41]:
torch.randperm(10)


 9
 1
 4
 7
 6
 0
 3
 5
 8
 2
[torch.LongTensor of size 10]

In [42]:
torch.get_num_threads()

1

[Link](http://pytorch.org/docs/master/torch.html) to docs. There's so much more you can do!